### PR TITLE
Add header with version to generated output file

### PR DESCRIPTION
**Pull request by nubbel**
Thank you for this awesome tool! 🎉
This PR adds a header to each generated file that includes the version of Insanity used to generate it.

Let me know what you think about it.

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
I like the idea, can we tweak the header to the following?
```
// Generated using Insanity \(version) — https://github.com/krzysztofzablocki/Insanity
// DO NOT EDIT
```

**Comment by nubbel** [comment]
@krzysztofzablocki Thanks for the quick response!
Of course, will do so now.

**Comment by nubbel** [comment]
Done!

Btw. the rationale behind that change is to make it easier to reproduce the output, which does not only depend on the input and template file, but also on the version of Insanity.
Additionally the warning in the second line should prevent unintentional edits to the generated files.
Should have stated that earlier…

**Comment by krzysztofzablocki** [comment]
Absolutely, it's a good idea and thank you very much for contributing 👍  
I'll merge this in the morning once CI passes (after midnight here)

**Comment by nubbel** [comment]
Yep, same here 🇩🇪. 
Good night! 🌙😴💤

**Pull request merged**
